import type { Capability, CapabilityGroup } from './schema'

export const capabilityGroups: readonly CapabilityGroup[] = [
  'Machine Learning',
  'MLOps and Infrastructure',
  'Data Engineering',
  'Cloud and Storage',
  'Evaluation',
  'Analytics',
  'Languages',
] as const

type Seed = readonly [name: string, depth: Capability['depth']]

const seeds: Record<CapabilityGroup, readonly Seed[]> = {
  'Machine Learning': [
    ['Python', 'daily'],
    ['PyTorch', 'daily'],
    ['TensorFlow', 'working'],
    ['scikit-learn', 'daily'],
    ['XGBoost', 'daily'],
    ['LightGBM', 'daily'],
    ['Hugging Face Transformers', 'daily'],
    ['Pandas', 'daily'],
    ['NumPy', 'daily'],
    ['SciPy', 'working'],
    ['statsmodels', 'working'],
    ['Feature engineering', 'daily'],
    ['Demand elasticity modeling', 'daily'],
    ['Time-series forecasting (ARIMA, Prophet)', 'daily'],
    ['NLP', 'daily'],
    ['Embeddings and vector search', 'working'],
  ],
  'MLOps and Infrastructure': [
    ['MLflow', 'daily'],
    ['Weights and Biases', 'working'],
    ['Databricks', 'daily'],
    ['Databricks Feature Store', 'daily'],
    ['Docker', 'daily'],
    ['Kubernetes', 'working'],
    ['Terraform', 'working'],
    ['FastAPI model serving', 'daily'],
    ['Blue-green deployment', 'daily'],
    ['Model monitoring and drift detection', 'daily'],
    ['Azure Pipelines', 'daily'],
    ['GitHub Actions', 'daily'],
    ['pytest', 'daily'],
    ['Automated A/B harnesses', 'daily'],
    ['Cookiecutter templating', 'daily'],
  ],
  'Data Engineering': [
    ['Delta Lake', 'daily'],
    ['Apache Spark', 'daily'],
    ['PySpark', 'daily'],
    ['Apache Airflow', 'daily'],
    ['Kafka', 'working'],
    ['Azure Event Hubs', 'working'],
    ['dbt', 'working'],
    ['ETL and ELT', 'daily'],
    ['Data validation and enrichment', 'daily'],
    ['Connector library design', 'daily'],
    ['Distributed training on Spark', 'daily'],
  ],
  'Cloud and Storage': [
    ['Azure Databricks', 'daily'],
    ['Azure Data Lake', 'daily'],
    ['Azure Pipelines', 'daily'],
    ['Azure Event Hubs', 'daily'],
    ['AWS S3', 'working'],
    ['AWS Redshift', 'working'],
    ['AWS Lambda', 'working'],
    ['GCP BigQuery', 'working'],
    ['GCP Dataflow', 'working'],
    ['GCP Pub/Sub', 'working'],
    ['PostgreSQL', 'daily'],
    ['MySQL', 'working'],
    ['Snowflake', 'working'],
    ['MongoDB', 'working'],
    ['Redis', 'working'],
    ['FAISS', 'working'],
    ['pgvector', 'working'],
  ],
  Evaluation: [
    ['RLHF', 'daily'],
    ['DPO', 'daily'],
    ['SFT', 'working'],
    ['Agentic trajectory evaluation', 'daily'],
    ['Tool-use grading', 'daily'],
    ['Rubric design', 'daily'],
    ['Adversarial prompting', 'daily'],
    ['Red-teaming', 'daily'],
    ['LLM-as-a-judge', 'daily'],
    ['Inter-annotator agreement', 'daily'],
  ],
  Analytics: [
    ['Power BI', 'daily'],
    ['Tableau', 'working'],
    ['Matplotlib', 'daily'],
    ['Seaborn', 'daily'],
    ['Plotly', 'working'],
    ['A/B testing', 'daily'],
    ['Cohort and funnel analysis', 'working'],
    ['Hypothesis testing', 'daily'],
  ],
  Languages: [
    ['Python', 'daily'],
    ['SQL', 'daily'],
    ['TypeScript and JavaScript', 'working'],
    ['Go', 'working'],
    ['Bash', 'daily'],
    ['R', 'working'],
  ],
}

export const capabilities: Capability[] = capabilityGroups.flatMap((group) =>
  (seeds[group] ?? []).map(([name, depth]) => ({ name, group, depth })),
)

export const capabilityLegend =
  'Filled square: in daily production use. Half square: working proficiency.'
