import type { Education, Role } from './schema'

export const roles: Role[] = [
  {
    id: 'walmart',
    title: 'AI/ML Engineer',
    company: 'Walmart',
    location: 'Remote',
    dates: 'November 2024 to Present',
    bullets: [
      'Built and operate the ML platform behind promotion and clearance pricing on Azure Databricks, Delta Lake and MLflow with Terraform-provisioned infrastructure, cutting research-to-production lead time 40 percent and serving over 200,000 predictions per month.',
      'Shipped PromotionsAI, driving 5.5 million dollars in incremental revenue in its first full fiscal year and 2.3 million the following quarter.',
      'Built and own the MLOps stack for ClearanceAI, lifting sell-through 4.6 percent.',
      'Standardized MLOps across both systems and the ingestion pipelines, cutting experiment turnaround 60 percent, holding a 99.9 percent SLA and halving incident MTTR.',
      'Automated ingestion, validation and enrichment with PySpark and Delta Lake and co-authored the reusable connector libraries, cutting new source onboarding 70 percent.',
    ],
    tech: [
      'Azure Databricks',
      'MLflow',
      'Delta Lake',
      'PySpark',
      'Terraform',
      'Kubernetes',
      'Docker',
      'Kafka',
      'XGBoost',
      'Python',
    ],
  },
  {
    id: 'contract-evaluation',
    title: 'AI Training and Evaluation Specialist',
    company: 'Contract',
    location: 'Remote',
    dates: 'November 2022 to Present',
    clients: [
      'Handshake AI',
      'Snorkel AI',
      'Mercor',
      'Outlier AI',
      'Alignerr',
      'Welocalize',
      'AfterQuery',
      'FleetAI',
      'SME Careers',
    ],
    bullets: [
      "Authored 200+ golden-solution software engineering tasks for Handshake AI's Project Helix, building multi-file repository problems with hidden test suites and graded difficulty tiers across Python, TypeScript and Go, and passed Helix Screening with a top-decile reviewer rating.",
      'Evaluated long-horizon coding-agent trajectories on real software workflows, scoring tool-use correctness, sub-goal decomposition, state tracking and recovery from failure, and surfaced systematic failures in tool-call sequencing and shell command grounding that fed directly into agent fine-tuning.',
      'Authored 50+ accepted Terminal-Bench tasks for Snorkel AI under the Terminus 2 agent scaffold: containerized environments with reference solutions and automated verification tests, calibrated to challenge frontier agents while staying unambiguous and solvable.',
      'Designed 150+ model-stumping prompts validated against GPT, Claude and Gemini-class baselines, plus graduate-level STEM question-answer pairs for reasoning benchmarks that passed multi-layer expert review.',
    ],
    tech: [
      'RLHF',
      'DPO',
      'SFT',
      'Agentic Evaluation',
      'Terminal-Bench',
      'Rubric Design',
      'Red-Teaming',
      'Python',
      'TypeScript',
      'Go',
    ],
  },
  {
    id: 'tech-mahindra',
    title: 'Software Engineer',
    company: 'Tech Mahindra',
    location: 'Hyderabad, India',
    dates: 'May 2023 to July 2024',
    bullets: [
      'Engineered ETL pipelines with Python, PySpark and Apache Airflow processing 50TB+ datasets for Fortune 500 clients, cutting data preparation time 45 percent and roughly 120 thousand dollars per year in cloud compute costs.',
      'Built ARIMA and Prophet time-series forecasting models at roughly 85 percent accuracy driving demand planning and budget allocation.',
      'Optimized data models through indexing and partitioning, cutting query execution time 60 percent for 200+ users, and ran A/B, cohort and funnel analyses informing 1.5 million dollars or more in strategic decisions.',
      'Automated 20+ Power BI and Tableau dashboards with scheduled refresh and row-level security, removing roughly 40 percent of manual reporting.',
    ],
    tech: [
      'Python',
      'PySpark',
      'Airflow',
      'SQL',
      'BigQuery',
      'PostgreSQL',
      'Power BI',
      'Tableau',
      'Prophet',
      'ARIMA',
    ],
  },
  {
    id: 'montclair',
    title: 'Data Analyst Intern (Part-Time)',
    company: 'Montclair State University',
    location: 'Montclair, NJ',
    dates: 'April 2025 to July 2025',
    bullets: [
      'Analyzed 114+ community engagement projects using statistical analysis, NLP and time-series methods.',
      'Built 20+ interactive dashboards in Python, Tableau and Power BI that cut report preparation time 40 percent.',
      'Applied text classification and sentiment analysis to 5,000+ qualitative survey responses, producing a strategic report presented at a multi-university conference.',
    ],
    tech: ['Python', 'Pandas', 'NumPy', 'SQL', 'NLP', 'Tableau', 'Power BI'],
  },
]

export const education: Education[] = [
  {
    degree: 'Master of Science, Data Science',
    school: 'Montclair State University',
    location: 'Montclair, NJ',
    date: 'May 2026',
  },
  {
    degree: 'Bachelor of Technology, Artificial Intelligence and Data Science',
    school: 'KL University',
    location: 'Hyderabad, India',
    date: 'April 2024',
  },
]
